class DailyDetailForm
  include ActiveModel::Model

  attr_accessor :interactor, :day, :code, :time_in, :time_out, :autogenerated

  validates :day, date: true, format: {with: /\A\d{4}-\d{2}-\d{2}\Z/}, type: {is_a: String}, allow_nil: true
  validates :code, type: {is_a: String}, allow_nil: true
  validates :time_in, :time_out, time: true, format: {with: /\A\d{2}:\d{2}\Z/, type: {is_a: String}}, allow_nil: true
  validates :autogenerated, inclusion: {in: [false, true]}, allow_nil: true
  validates :autogenerated, inclusion: {in: [false, true]}, if: :submitted?
  validates :day, :code, presence: true, if: :submitted?
  validates :time_in, :time_out, presence: true, if: -> { submitted? and simplified? }

  def submitted?
    interactor.present? and interactor.submitted?
  end

  def simplified?
    interactor.present? and interactor.simplified?
  end

  def as_json
    super(only: %w[day code time_in time_out autogenerated])
  end
end
