describe("details generator", function () {
    var injector, detailsGenerator;

    beforeEach(function () {
        injector = angular.injector(["ng", "ngMock", "moBilling"]);
        detailsGenerator = injector.get("detailsGenerator");
    });

    it("returns empty array for empty claim", function () {
        expect(detailsGenerator({})).toEqual([]);
    });

    it("returns correct codes #1", function () {
        var details,
            claim = {
                admission_on: "2014-06-09",
                first_seen_on: "2014-06-09",
                last_seen_on: "2014-07-20",
                last_seen_discharge: true,
                most_responsible_physician: true,
                consult_type: "general_er"
            };

        details = detailsGenerator(claim);

        expect(details[0]).toEqual({ day : "2014-06-09", code : "A135", autogenerated : true });
        expect(details[1]).toEqual({ day : "2014-06-09", code : "E082", autogenerated : true });
    });
});
