class Claim
  class DailyDetail
    include ActiveModel::Model

    attr_accessor :interactor, :day, :code, :autogenerated

    validates :day, date: true, format: {with: /\A\d{4}-\d{2}-\d{2}\Z/}, type: {is_a: String}, allow_nil: true
    validates :code, type: {is_a: String}, allow_nil: true
    validates :autogenerated, inclusion: {in: [false, true]}, allow_nil: true
    validates :autogenerated, inclusion: {in: [false, true]}, if: :submitted?
    validates :day, :code, presence: true, if: :submitted?

    def submitted?
      interactor.present? and interactor.submitted?
    end

    def as_json
      super(only: %w[day code autogenerated])
    end
  end
end
