require "test_helper"

class UpdateClaimTest < ActiveSupport::TestCase
  setup do
    @user = create(:user)
    @claim = create(:claim, specialty: "internal_medicine")
    @form = ClaimForm.new(@claim, status: "saved")
    @form.user = @user
  end

  test "performs properly" do
    assert @form.perform
    assert @form.claim.persisted?
  end

  test "performs properly with for_agent status" do
    @form.status = "for_agent"
    @form.photo_id = create(:photo).id
    @form.patient_name = "Alice"
    @form.hospital = "Ottawa"
    @form.diagnoses = [{name: "Flu"}]
    @form.most_responsible_physician = true
    @form.admission_on = 1.week.ago.to_date.to_s
    @form.first_seen_on = 3.days.ago.to_date.to_s
    @form.first_seen_consult = true
    @form.last_seen_on = 1.day.ago.to_date.to_s
    @form.last_seen_discharge = false
    @form.icu_transfer = false
    @form.consult_type = "comprehensive_er"
    @form.consult_time_in = "17:00"
    @form.consult_time_out = "20:00"
    @form.consult_premium_visit = "holiday_day"
    @form.consult_premium_first = true
    @form.consult_premium_travel = true
    @form.daily_details = [{day: "2014-06-30", code: "E082", autogenerated: true}]
    @form.comment = "A comment"
    assert @form.perform
    assert @form.claim.persisted?
    assert_equal 1, @form.claim.comments.count
    assert_equal "A comment", @form.claim.comments.first.body
  end

  test "does not change number when already set" do
    @form.status = "for_agent"
    @form.photo_id = create(:photo).id
    @form.patient_name = "Alice"
    @form.hospital = "Ottawa"
    @form.diagnoses = [{name: "Flu"}]
    @form.most_responsible_physician = true
    @form.admission_on = 1.week.ago.to_date.to_s
    @form.first_seen_on = 3.days.ago.to_date.to_s
    @form.first_seen_consult = false
    @form.last_seen_on = 1.day.ago.to_date.to_s
    @form.last_seen_discharge = false
    @form.icu_transfer = false
    @form.daily_details = [{day: "2014-06-30", code: "E082", autogenerated: true}]
    @form.valid?
    old_number = @claim.number
    assert @form.perform
    assert_equal old_number, @form.claim.number
  end
end
